
# Site settings
title: Artificial Intelligence and Statistics Conference
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "/aistats2011" # the subpath of your site, e.g. /blog/
url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat

github_username:  aistats
author:
  name: AISTATS
comments: false
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings

ghub:
  edit: true
  repository: aistats.github.io
banner:
  image: resort.jpg

# Build settings
markdown: kramdown

conference:
  draft: false # set to True if the programme is draft only.
  logo: logo.jpg
  hide_tentative: true
  proceedings:
    url: http://proceedings.mlr.press/v15/
    show: true
  room: Room
  venue: Hyatt Regency Pier 66
  venue_url: https://www.pier66hotelmarina.com/
  location: Ft. Lauderdale, FL, USA
  full_name: Artificial Intelligence and Statistics
  name: AISTATS
  year: 2011
  instance: 14th
  styling: International Conference on
  dates:
  - 2011-04-11
  - 2011-04-13

# change encoding for the generated output files to utf-8
encoding: utf-8


